main:
  params: []
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - job_location: europe-north1
          - job_namespace: ${"namespaces/" + project_id + "/jobs/"}
          - bucket: ${sys.get_env("BUCKET")}
    - loop:
        for:
          value: i
          range: ${[0, 100]}
          steps:
            - upload:
                call: googleapis.run.v1.namespaces.jobs.run
                args:
                  name: ${job_namespace + "google-cloud-storage-ssl-error"}
                  location: ${job_location}
                  body:
                    overrides:
                      containerOverrides:
                        args:
                          - ${bucket}
                          - --folder
                          - testfolder
